// Import every *.test.ts here so one bundle runs the whole suite.
import { summary } from "./assert";

// (test files imported below as they are added)
import "./conformal.test";
import "./droste-layout.test";
import "./note-menu.test";

import "./theme.test";
import "./query.test";
import "./image-export.test";
import "./tag-classification.test";
import "./lens-presets.test";
import "./preset-io.test";
import "./svg-recorder.test";
import "./shape-channel.test";
import "./draw-shape.test";
import "./canvas-utils.test";
import "./draw-card-fill.test";
import "./legend-layout.test";
import "./legend-spec.test";
import "./mode-legend.test";
import "./mode-legend-input.test";
import "./bundled-presets.test";
import "./freshness.test";
import "./gap-finder.test";
import "./bridge-finder.test";


import "./status-overlay.test";
import "./note-maturity.test";
import "./heatmap-layout.test";
import "./scatter-layout.test";
import "./display-applicability.test";
import "./encoding-scales.test";
import "./encoding-evaluate.test";
import "./encoding-migrate.test";
import "./axis-layout.test";
import "./scatter-axis-defaults.test";
import "./droste-axis.test";
import "./spreadsheet-pan.test";
import "./insight-alerts.test";
import "./tag-path.test";
import "./note-menu-geom.test";
import "./view-shell-style.test";
import "./settings-sub-tabs.test";
import "./view-mode-picker.test";
import "./jaccard-input.test";
import "./min-font-input.test";
import "./heatmap-min-tag-input.test";
import "./node-size-input.test";
import "./bases-edge-kinds.test";
import "./scatter-axis-options.test";
import "./scatter-axis-binding.test";
import "./bases-toggle-rows.test";
import "./inherit-from-options.test";
import "./settings-toggle-rows.test";
import "./zoom-math.test";
import "./hit-modes.test";
import "./hit-test-aggregation.test";
import "./settings-parity.test";
import "./attribute-propagation.test";
import "./euler-true-stripes.test";
import "./bubblesets-sibling-overlap.test";
import "./aggregation-compute.test";
import "./aggregation-properties.test";
import "./bases-parser.test";
import "./bases-resolve.test";
import "./bases-containsany-smoke.test";
import "./bases-relations.test";
import "./bases-project.test";

import "./bases-fallback.test";
import "./bases-selection.test";
import "./bases-skip-postprocess.test";
import "./friendly-error.test";
import "./tag-field-suggest.test";
import "./query-builder.test";
import "./label-collision.test";
import "./bubblesets-label-collision.test";
import "./bubblesets-invariants.test";
import "./bubblesets-render-smoke.test";
import "./scatter-render-smoke.test";
import "./all-modes-render-smoke.test";
import "./lattice-draw-input.test";
import "./droste-draw-input.test";
import "./heatmap-draw-input.test";
import "./upset-draw-input.test";
import "./enclosure-draw-input.test";
import "./edge-draw-plan.test";
import "./node-draw-list.test";
import "./junihitoe-stack-list.test";
import "./aggregate-stack-list.test";
import "./view-line-ratchet.test";
import "./pluralize.test";
import "./jaccard.test";
import "./tab-prefix.test";
import "./heatmap-detail.test";
import "./hover-tip-text.test";
import "./clamp-zoom.test";
import "./content-bounds.test";
import "./point-in-rect.test";


summary();
