// Import every *.test.ts here so one bundle runs the whole suite.
import { summary } from "./assert";

// (test files imported below as they are added)
import "./conformal.test";
import "./droste-layout.test";
import "./note-menu.test";
import "./hidden-nodes.test";
import "./theme.test";
import "./query.test";
import "./image-export.test";
import "./tag-classification.test";
import "./lens-presets.test";
import "./preset-io.test";
import "./svg-recorder.test";
import "./shape-channel.test";
import "./draw-shape.test";
import "./canvas-utils.test";
import "./draw-card-fill.test";
import "./legend-layout.test";
import "./legend-spec.test";
import "./mode-legend.test";
import "./bundled-presets.test";
import "./freshness.test";
import "./gap-finder.test";
import "./bridge-finder.test";
import "./having-highlight.test";
import "./having-auto-seed.test";
import "./status-overlay.test";
import "./note-maturity.test";
import "./stream-layout.test";
import "./heatmap-layout.test";
import "./display-applicability.test";
import "./encoding-scales.test";
import "./encoding-evaluate.test";
import "./encoding-migrate.test";
import "./axis-layout.test";
import "./droste-axis.test";
import "./spreadsheet-pan.test";
import "./insight-alerts.test";
import "./tag-path.test";
import "./note-menu-geom.test";
import "./zoom-math.test";
import "./hit-modes.test";
import "./settings-parity.test";
import "./attribute-propagation.test";
import "./euler-true-stripes.test";
import "./aggregation-compute.test";
import "./aggregation-properties.test";
import "./bases-parser.test";
import "./bases-resolve.test";
import "./bases-relations.test";
import "./bases-project.test";
import "./bases-mode-gate.test";

summary();
